services:
  - type: web
    name: seafood-api
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: node dist/src/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
    autoDeploy: true
